[supabase]
url = "https://ywtavuwekwxewdfbynid.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dGF2dXdla3d4ZXdkZmJ5bmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3MzI2ODgsImV4cCI6MjA5MzMwODY4OH0._RdTq-E9Zt6cbSBgHn07qs7mZSVt9EEF7NsMjszAflo"
